# Generated by Django 3.1.4 on 2020-12-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
