# Generated by Django 3.1.4 on 2020-12-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='_category_category_+', to='shop.Category'),
        ),
    ]
