# Generated by Django 3.1.4 on 2020-12-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20201218_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='_category_category_+', to='shop.Category'),
        ),
    ]
